log_registry: null
version: 1
loggers:
  SingleTableSynthesizer:
    level: INFO
    propagate: false
    format: CSV
    handlers:
      class: logging.FileHandler
      filename: sdv_logs.csv
  MultiTableSynthesizer:
    level: INFO
    propagate: false
    format: CSV
    handlers:
      class: logging.FileHandler
      filename: sdv_logs.csv
    MultiTableMetadata:
      level: INFO
      propagate: false
      format: CSV
      handlers:
        class: logging.FileHandler
        filename: sdv_logs.csv
    SingleTableMetadata:
      level: INFO
      propagate: false
      format: CSV
      handlers:
        class: logging.FileHandler
        filename: sdv_logs.csv
