{% set name = 'sdv' %}
{% set version = '0.7.1.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - graphviz
    - numpy >=1.17.4,<2
    - pandas >=1.1,<1.1.5
    - python-graphviz >=0.13.2,<2.42.4
    - ctgan >=0.3.1,<0.4
    - copulas >=0.4.0,<0.5
    - rdt >=0.2.10,<0.4
    - sdmetrics >=0.1.2,<0.2
    - deepecho >=0.1.4,<0.2
  run:
    - python
    - graphviz
    - numpy >=1.17.4,<2
    - pandas >=1.1,<1.1.5
    - python-graphviz >=0.13.2,<2.42.4
    - ctgan >=0.3.1,<0.4
    - copulas >=0.4.0,<0.5
    - rdt >=0.2.10,<0.4
    - sdmetrics >=0.1.2,<0.2
    - deepecho >=0.1.4,<0.2


about:
  home: "https://sdv.dev"
  license: MIT
  license_family: MIT
  license_file: "LICENSE"
  summary: "Synthetic Data Generation for tabular, relational and time series data."
  doc_url: "https://sdv.dev/SDV"
  dev_url: "https://github.com/sdv-dev/SDV"

extra:
  recipe-maintainers:
    - sdv-dev
