{% set name = "xeger" %}
{% set version = "0.3.5" %}

package:
  name: "{{ name|lower }}"
  noarch: python
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "https://github.com/crdoconnor/xeger"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A library for generating random strings from a valid regular expression."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - sdv-dev
